apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-cm
data:
  app-config: |
    log-file = "/var/log/miniapp.log"
    log-level = "info"
    listen-port = "8000"

    [db-config]
    host = "my-release-postgresql.miniapp.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432
  init_db.sh: |
    #!/bin/bash
    if [[ $(hostname) == *primary* ]]; then
        echo "Primary node"
        
        password_aux="${MYSQL_ROOT_PASSWORD:-}"
        if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
            password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
        fi

        mysql -P 3306 -uroot -p"$password_aux" -e "
            create database if not exists miniapp;
            use miniapp;
            CREATE TABLE IF NOT EXISTS users (
            id INT AUTO_INCR EMENT PRIMARY KEY,
            username VARCHAR(256) NOT NULL UNIQUE,
            firstname VARCHAR(256) NOT NULL,
            lastname VARCHAR(256) NOT NULL,
            email VARCHAR(256) NOT NULL UNIQUE,
            phone VARCHAR(256) NOT NULL UNIQUE
            );
            create user if not exists 'miniapp'@'%' identified by '{$MYSQL_PASSWORD}';
            grant select, insert, update, delete on users to 'miniapp'@'%';
            flush privileges;"
    else
        echo "Secondary node"
    fi
