definitions:
  types.CreateOrderResponse:
    properties:
      id:
        type: integer
    type: object
  types.HTTPError:
    properties:
      error:
        type: string
    type: object
  types.Item:
    properties:
      id:
        type: integer
      orderID:
        format: int64
        type: integer
      quantity:
        type: integer
      stockID:
        format: int64
        type: integer
    type: object
  types.Order:
    properties:
      address:
        type: string
      ctime:
        type: string
      end_time:
        type: string
      error:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/types.Item'
        type: array
      mtime:
        type: string
      start_time:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: This is order service API.
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: Order API
  version: "1.0"
paths:
  /create_order:
    post:
      consumes:
      - application/json
      description: create order
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.CreateOrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.HTTPError'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/types.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.HTTPError'
      summary: create order
      tags:
      - order
  /get_orders:
    get:
      description: get orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Order'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.HTTPError'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/types.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.HTTPError'
      summary: get orders
      tags:
      - order
swagger: "2.0"
