image:
  debug: true

auth:
  existingSecret: kuber-secret

primary:
  initdb:
    scripts:
      init.sql: |
        CREATE DATABASE miniapp;
        \c miniapp;
        CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            username VARCHAR(256) NOT NULL UNIQUE,
            firstname VARCHAR(256) NOT NULL,
            lastname VARCHAR(256) NOT NULL,
            email VARCHAR(256) NOT NULL UNIQUE,
            phone VARCHAR(256) NOT NULL UNIQUE
        );